
name: Express Project
services: 
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432 # Expose PostgreSQL port


  # Express app
  express-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_api
    restart: always
    ports:
      - 3000:3000 # Expose Express app port
      - 5555:5555 # Expose Prisma port
    depends_on:
      - postgres # Ensure PostgreSQL is started before the Express app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
